In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [4]:
img = cv2.imread('E:/CV/week 1/lenna.jpg')
cv2.imshow('lenna',img)
key = cv2.waitKey()
if key == 27:
    cv2.destoryALLWindows()
    

In [5]:
print(img)

[[[114 134 229]
  [113 133 228]
  [113 133 228]
  ...
  [123 135 229]
  [137 152 244]
  [103 112 209]]

 [[113 133 228]
  [113 133 228]
  [113 133 228]
  ...
  [124 132 225]
  [141 149 239]
  [109 111 205]]

 [[113 133 228]
  [113 133 228]
  [113 133 228]
  ...
  [106 107 197]
  [111 107 196]
  [ 87  73 161]]

 ...

 [[ 65  28  84]
  [ 65  29  89]
  [ 65  29  95]
  ...
  [ 74  51 126]
  [ 77  58 139]
  [ 78  61 152]]

 [[ 60  25  81]
  [ 59  25  85]
  [ 60  24  90]
  ...
  [ 77  57 134]
  [ 84  66 149]
  [ 77  66 159]]

 [[ 54  25  81]
  [ 60  30  89]
  [ 61  27  92]
  ...
  [ 89  71 154]
  [ 91  76 167]
  [ 85  74 176]]]


In [6]:
print(img.dtype)

uint8


In [7]:
print(img.shape)

(225, 225, 3)
