In [2]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

img_gray = cv2.imread('E:\CV\week 1\lenna.jpg',0)
cv2.imshow('lenna',img_gray)

key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()
print(img_gray)

[[160 159 159 ... 162 178 140]
 [159 159 159 ... 159 175 139]
 [159 159 159 ... 134 134 101]
 ...
 [ 49  51  53 ...  76  84  90]
 [ 46  47  48 ...  82  93  95]
 [ 45  51  50 ...  98 105 106]]


In [3]:
print(img_gray.dtype)

uint8


In [4]:
print(img_gray)

[[160 159 159 ... 162 178 140]
 [159 159 159 ... 159 175 139]
 [159 159 159 ... 134 134 101]
 ...
 [ 49  51  53 ...  76  84  90]
 [ 46  47  48 ...  82  93  95]
 [ 45  51  50 ...  98 105 106]]


In [5]:
print(img_gray.shape)

(225, 225)
